// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ramon_Lopez_AP1_P2.Dal;

#nullable disable

namespace Ramon_Lopez_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250714232617_CambiaNombreDeCampo")]
    partial class CambiaNombreDeCampo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ramon_Lopez_AP1_P2.Models.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntradaId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Ramon_Lopez_AP1_P2.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("EntradasDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntradasDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("EntradaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("EntradasDetalleId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Ramon_Lopez_AP1_P2.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsCompuesto")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Existencia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripcion = "Maní",
                            EsCompuesto = false,
                            Existencia = 100.0m,
                            Peso = 5.00m
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripcion = "Almendra",
                            EsCompuesto = false,
                            Existencia = 75.0m,
                            Peso = 10.00m
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripcion = "Pistacho",
                            EsCompuesto = false,
                            Existencia = 50.0m,
                            Peso = 20.00m
                        });
                });

            modelBuilder.Entity("Ramon_Lopez_AP1_P2.Models.EntradasDetalle", b =>
                {
                    b.HasOne("Ramon_Lopez_AP1_P2.Models.Entradas", "Entradas")
                        .WithMany("EntradasDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ramon_Lopez_AP1_P2.Models.Productos", "Productos")
                        .WithMany("EntradasDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entradas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Ramon_Lopez_AP1_P2.Models.Entradas", b =>
                {
                    b.Navigation("EntradasDetalle");
                });

            modelBuilder.Entity("Ramon_Lopez_AP1_P2.Models.Productos", b =>
                {
                    b.Navigation("EntradasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
